config/routes.rb
Spacescout::Application.routes.draw do
  resources :reservations
  
  get "/profile" => 'users#profile', :as => :profile

  get "sessions/new", :as => :signin
  post "sessions/create"
  get "sessions/destroy", :as => :signout
  
  resources :spaces

  resources :users
  
  get "spaces/index" => 'spaces#index', :as => :spaces

  root to: 'spaces#index'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :date, :space_id, :user_id
end

app/models/space.rb
class Space < ActiveRecord::Base
  attr_accessible :amenities, :description, :hours, :location, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :industry, :name, :password, :password_confirmation, :password_digest

  has_secure_password
  
  has_many :reservations
  has_many :spaces, :through => :reservations

  # scope :admins, where(:admin => true)
  #  scope :nonadmins, where(:admin => false)

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservations }
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/new
  # GET /reservations/new.json
  def new
    @reservation = Reservation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/1/edit
  def edit
    @reservation = Reservation.find(params[:id])
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(params[:reservation])

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render json: @reservation, status: :created, location: @reservation }
      else
        format.html { render action: "new" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservations/1
  # PUT /reservations/1.json
  def update
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user
      if user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to user_url(user), notice: "Welcome Back!"
      else
        redirect_to root_url, notice: "Wrong password!"
      end
    else
      redirect_to root_url, notice: "Wrong email address!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  # GET /spaces
  # GET /spaces.json
  def index
    @spaces = Space.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spaces }
    end
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
    @space = Space.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @space }
    end
  end

  # GET /spaces/new
  # GET /spaces/new.json
  def new
    @space = Space.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @space }
    end
  end

  # GET /spaces/1/edit
  def edit
    @space = Space.find(params[:id])
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(params[:space])

    respond_to do |format|
      if @space.save
        format.html { redirect_to @space, notice: 'Space was successfully created.' }
        format.json { render json: @space, status: :created, location: @space }
      else
        format.html { render action: "new" }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spaces/1
  # PUT /spaces/1.json
  def update
    @space = Space.find(params[:id])

    respond_to do |format|
      if @space.update_attributes(params[:space])
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space = Space.find(params[:id])
    @space.destroy

    respond_to do |format|
      format.html { redirect_to spaces_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Space Scout</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<div id="container">
		<header>
			<h1><%= link_to "Space Scout", root_url %></h1>
			<nav>
				<ul>
					<% if session[:user_id] %>
						<li><%= link_to "View My Profile", profile_url %></li>
						<li><%= link_to "Sign Out", signout_url %></li>
					<% else %>
						<li><%= link_to "Join Us", new_user_url %></li>
						<li><%= link_to "Sign In", signin_url %></li>
					<% end %>
				</ul>
			</nav>
			<p>
			  <% if session[:user_id] %>
			    <% u = User.find_by_id(session[:user_id]) %>
			    Hello, <%= u.name %>
			 <% end %>
			</p>
		</header>

		<div id="content">
			<%= yield %>
		</div>
		
		<footer>
			&copy;2012 Space Scout.  Follow us on Twitter!
		</footer>
	</div>
</body>
</html>

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :space_id %><br />
    <%= f.text_field :space_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<h1>Listing reservations</h1>

<table>
  <tr>
    <th>Date</th>
    <th>User</th>
    <th>Space</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reservations.each do |reservation| %>
  <tr>
    <td><%= reservation.date %></td>
    <td><%= reservation.user_id %></td>
    <td><%= reservation.space_id %></td>
    <td><%= link_to 'Show', reservation %></td>
    <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
    <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @reservation.date %>
</p>

<p>
  <b>User:</b>
  <%= @reservation.user_id %>
</p>

<p>
  <b>Space:</b>
  <%= @reservation.space_id %>
</p>


<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

app/views/spaces/_form.html.erb
<%= form_for(@space) do |f| %>
  <% if @space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
      <% @space.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :hours %><br />
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label :amenities %><br />
    <%= f.text_field :amenities %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spaces/edit.html.erb
<h1>Editing space</h1>

<%= render 'form' %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

app/views/spaces/index.html.erb
<%= notice %>

<h1>Listing spaces</h1>

<div id="search">
  <%= form_tag spaces_url, method: :get do %>
	<label for="keyword">Search:</label><input type="text" name="keyword" placeholder="Enter Zip Code" size="14">
  <%= submit_tag 'Search' %>
  <% end %>
</div>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Hours</th>
    <th>Amenities</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spaces.each do |space| %>
  <tr>
    <td><%= space.name %></td>
    <td><%= space.location %></td>
    <td><%= space.hours %></td>
    <td><%= space.amenities %></td>
    <td><%= space.description %></td>
  </tr>
<% end %>
</table>

app/views/spaces/new.html.erb
<h1>New space</h1>

<%= render 'form' %>

<%= link_to 'Back', spaces_path %>

app/views/spaces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @space.name %>
</p>

<p>
  <b>Location:</b>
  <%= @space.location %>
</p>

<p>
  <b>Hours:</b>
  <%= @space.hours %>
</p>

<p>
  <b>Amenities:</b>
  <%= @space.amenities %>
</p>

<p>
  <b>Description:</b>
  <%= @space.description %>
</p>


<%= link_to 'Edit', edit_space_path(@space) %> |
<%= link_to 'Back', spaces_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br />
    <%= f.text_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :industry %><br />
    <%= f.text_field :industry %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Name</th>
    <th>Password</th>
    <th>Password digest</th>
    <th>Password confirmation</th>
    <th>Industry</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.name %></td>
    <td><%= user.password %></td>
    <td><%= user.password_digest %></td>
    <td><%= user.password_confirmation %></td>
    <td><%= user.industry %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>

<p>
  <b>Password confirmation:</b>
  <%= @user.password_confirmation %>
</p>

<p>
  <b>Industry:</b>
  <%= @user.industry %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>